module.exports = {
    "boost": ["Boosting engines.", "Boosting.", "Engaging Boost."],
	"youThere": ["I'm here and ready to help.", "I'm here.", "Ready to help."],
	"balencePower": ["Balancing power.", "Balancing."],
	"cancelDocking": ["Cancelling docking request."],
	"cargoScan": ["Scanning cargo."],
	"deployChaff": ["Deploying chaff."],
	"deployHardpoints": ["Deploying weapons.", "Weapons."],
	"deployLandingGear": ["Deploying landing gear.", "Gear coming down.", "Landing gear going down.", "Gear going down."],
	"deployCargoScoop": ["Deploying cargo scoop.", "Lowering scoop.", "Lowering cargo scoop"],
	"deploySRV": ["Deploying SRV.", "Let's go driving"],
	"exitFrameShift": ["Exiting frame shift drive.", "Disengaging frame shift.", "Disengaging frame shift drive.", "Exiting frame shift."],
	"exitCruise": ["Exiting supercruise.", "Disengaging cruise.", "Disengaging supercruise.", "Exiting cruise."],
	"powerToEngines": ["Diverting power to engines.","Power to engines.","Diverting.", "Diverting Power"],
	"powerToSystems": ["Diverting power to systems.", "Power to systems.","Diverting.", "Diverting Power"],
	"powerToWeapons": ["Diverting power to weapons.", "Power to weapons.","Diverting.", "Diverting Power"],
	"emergencyStop": ["Initializing emergency stop."],
	"engageFrameShift": ["Engaging frameshift drive.", "Engaging frameshit.", "Frameshit.", "Frameshift drive"],
	"engageCruise": ["Engaging supercruise.", "Supercruise"],
	"flightAssistOff": ["Turning fight assist off."],
	"flightAssistOn": ["Turning flight assist on."],
	"Screenshot": ["Taking screenshot.", "Taking picture."],
	"targetEnemy": ["Targeting enemy.", "Highlighting.", "Targeting.", "Time to fight!"],
	"launch": ["Preparing to launch."],
	"lightsOn": ["Turning lights on.", "Lights on."],
	"lightsOff": ["Turning lights off.", "Lights off."],
	"enginesForwardOneHundredPercent": ["Engines one hundred percent."],
	"enginesForwardNintyPercent": ["Engines ninty percent."],
	"enginesForwardEightyPercent": ["Engines eighty percent."],
	"enginesForwardSeventyFivePercent": ["Engines seventy five percent."],
	"enginesForwardSeventyPercent": ["Engines seventy percent."],
	"enginesForwardSixtyPercent": ["Engines sixty percent."],
	"enginesForwardFiftyPercent": ["Engines fifty percent."],
	"enginesForwardFortyPercent": ["Engines forty percent."],
	"enginesForwardThirtyPercent": ["Engines thrity percent."],
	"enginesForwardTwentyFivePercent": ["Engines twenty five percent."],
	"enginesForwardTwentyPercent": ["Engines twenty percent."],
	"enginesForwardTenPercent": ["Engines ten percent."],
	"nextFireGroup": ["Selecting next fire group.", "Cycling next fire group.", "Switching fire groups."],
	"nextHostile": ["Targeting next hostile.", "Cycling next hostile.", "Targeting."],
	"nextSystem": ["Selecting next star system.", "Cycling next system.", "Selecting."],
	"nextShip": ["Selecting next ship.", "Next ship."],
	"prevFireGroup": ["Changing to previous fire group.", "Selecting previous fire group.", "Cycling previous fire group.", "Switching fire groups."],
	"prevHostile": ["Targeting previous hostile.", "Cycling previous hostile.", "Targeting."],
	"prevShip": ["Selecting previous ship.", "Previous ship."],
	"dockingRequest": ["Requesting docking.", "Sending docking request."],
	"diognostics": ["All good"],
	"centerHeadset": ["Centering headset."],
	"retractHardpoints": ["Retracting hardpoints."],
	"retractLandingGear": ["Retracting landing gear.", "Retracting landing gear."],
	"retractCargoScoop": ["Retracting cargo scoop.", "Retracting scoop."],
	"enginesBackwardOneHundredPercent": ["Setting engines to one hundred percent backward."],
	"enginesBackwardSeventyFivePercent": ["Setting engines to seventy five percent backward."],
	"enginesBackwardFiftyPercent": ["Setting engines to fifty percent backward."],
	"enginesBackwardTwentyFivePercent": ["Setting engines to twenty five percent backward."],
	"SRVRecovery": ["Recovering SRV."],
	"stopEngines": ["Cutting engines."],
	"whatsNext": [" Whats next?"],
	"thankYou": ["You're welcome."],
	"thatsAll": ["Okay."],
	"unknownIntent": ["I don't know what you said."]
};






